logLevel: info
api: yes
apiAddress: :9997
metrics: yes
metricsAddress: :9998
rtspAddress: :8554
webrtcAddress: :8889
webrtcAllowOrigins: ["*"]
hls: yes
hlsAddress: :8888
hlsAllowOrigins: ["*"]
hlsVariant: lowLatency

paths:
  dog-cam:
    source: publisher
